const APP = Object.freeze({
  NAME: 'ReparaPRO Gastos',
  VERSION: '1.8.0',
  SPREADSHEET_ID: '1ivQ30ZjxNEMOXZCZEordOZFOVJopQS6xTj8Iy4m4yvU',
  INVOICE_FOLDER_ID: '1hv9U-HJxLkLSB__IBnbLl02lCzqEOgu5',
  BANK_FOLDER_ID: '1Lo92j-ol_ZuAaq-6Uioi-eh60jBP_S5l',
  OWNER_EMAIL: 'compras@reparapro.com',
  TIMEZONE: 'Europe/Madrid',
  MAX_BATCH_SIZE: 20,
  SLICE_SIZE: 5,
  EXECUTION_BUDGET_MS: 210000,
  START_DATE: '2026-07-18',
  MAX_UPLOAD_BYTES: 12 * 1024 * 1024,
  SHEETS: Object.freeze({
    CONFIG: 'CONFIG', PROVIDERS: 'PROVEEDORES', RULES: 'REGLAS', INVOICES: 'FACTURAS', LOG: 'LOG',
    BATCHES: 'LOTES', DOCUMENTS: 'DOCUMENTOS', MOVEMENTS: 'MOVIMIENTOS', RECONCILIATIONS: 'CONCILIACIONES',
    CATEGORIES: 'CATEGORIAS', EXPORTS: 'EXPORTACIONES',
  }),
});

const HEADERS = Object.freeze({
  CONFIG: ['CLAVE', 'VALOR', 'DESCRIPCIÓN'],
  PROVEEDORES: ['PROVEEDOR', 'DOMINIO', 'CIF_NIF', 'TIPO', 'ACTIVO', 'OBSERVACIONES', 'ID_PROVEEDOR', 'ALIASES', 'EVIDENCIA', 'FECHA_ACTUALIZACION', 'ACTUALIZADO_POR', 'REQUEST_ID'],
  REGLAS: ['PROVEEDOR', 'CAMPO', 'TEXTO_O_PATRÓN', 'PRIORIDAD', 'ACTIVA'],
  FACTURAS: ['FECHA_FACTURA', 'PROVEEDOR', 'CIF_NIF', 'NÚMERO_FACTURA', 'IMPORTE_TOTAL', 'MONEDA', 'ESTADO', 'ARCHIVO_DRIVE', 'URL_DRIVE', 'REMITENTE', 'ASUNTO', 'FECHA_PROCESO', 'OBSERVACIONES', 'FECHA_CORREO', 'NOMBRE_ORIGINAL', 'MOTIVO_REVISION', 'REFERENCIA_CORREO', 'ID_UNICO', 'HASH_PDF', 'LOTE_ID', 'USUARIO_DECISION', 'FECHA_DECISION', 'EVIDENCIA_JSON', 'VERSION_ESQUEMA', 'PROVEEDOR_NO_HABITUAL', 'FECHA_OPERACION', 'FECHA_VENCIMIENTO', 'CATEGORIA_ID', 'BASE_IMPONIBLE', 'IMPUESTOS_JSON', 'NOTA_INTERNA', 'ESTADO_CONCILIACION', 'IMPORTE_ASIGNADO'],
  LOG: ['FECHA_HORA', 'NIVEL', 'ACCIÓN', 'DOCUMENTO', 'DETALLE', 'DATOS_JSON', 'USUARIO', 'LOTE_ID', 'ID_EVENTO'],
  LOTES: ['LOTE_ID', 'TIPO', 'ESTADO', 'FECHA_DESDE', 'FECHA_HASTA', 'MAX_CORREOS', 'CORREOS_REVISADOS', 'PDF_ENCONTRADOS', 'CURSOR', 'PENDING_MESSAGE_IDS_JSON', 'PENDING_NEXT_CURSOR', 'CORREOS_PROCESADOS_JSON', 'PROGRESO', 'CREADO_EN', 'CREADO_POR', 'APROBADO_EN', 'APROBADO_POR', 'ERROR', 'REQUEST_ID', 'FECHA_BUSQUEDA', 'CURSOR_DIA', 'PENDING_SCAN_IDS_JSON', 'CANDIDATOS_DIA_JSON', 'ESCANEO_DIA_COMPLETO', 'CANCELADO_EN', 'CANCELADO_POR', 'MOTIVO_CANCELACION'],
  DOCUMENTOS: ['DOCUMENTO_ID', 'LOTE_ID', 'MESSAGE_ID', 'ATTACHMENT_ID', 'SOURCE_KEY', 'NOMBRE_ORIGINAL', 'REMITENTE', 'ASUNTO', 'FECHA_CORREO', 'FECHA_FACTURA', 'PROVEEDOR', 'PROVEEDOR_ID', 'CIF_NIF', 'NUMERO_FACTURA', 'IMPORTE_TOTAL', 'MONEDA', 'FASE', 'ESTADO_PROPUESTO', 'ESTADO_FINAL', 'MOTIVO_REVISION', 'EVIDENCIA_JSON', 'HASH_PDF', 'GMAIL_URL', 'SELECCIONADO', 'ACTUALIZADO_EN', 'ACTUALIZADO_POR', 'ERROR', 'REQUEST_ID', 'ARCHIVO_DRIVE', 'URL_DRIVE', 'DRIVE_FILE_ID', 'DESTINATARIOS', 'DIRECCION_CORREO', 'PROVEEDOR_NO_HABITUAL', 'FECHA_OPERACION', 'FECHA_VENCIMIENTO', 'CATEGORIA_ID', 'BASE_IMPONIBLE', 'IMPUESTOS_JSON', 'NOTA_INTERNA', 'MOTIVO_DECISION', 'ERRORES_VALIDACION_JSON'],
  MOVIMIENTOS: ['MOVIMIENTO_ID', 'IMPORT_ID', 'ARCHIVO_NOMBRE', 'ARCHIVO_HASH', 'RAW_FILE_ID', 'URL_DRIVE', 'FUENTE', 'PERIODO_DESDE', 'PERIODO_HASTA', 'COBERTURA', 'ESTADO_IMPORTACION', 'FECHA_OPERACION', 'FECHA_VALOR', 'CONCEPTO', 'IMPORTE', 'MONEDA', 'REFERENCIA', 'TIPO', 'ESTADO_CONCILIACION', 'FACTURA_CANDIDATA_ID', 'EVIDENCIA', 'CREADO_EN', 'CREADO_POR', 'REQUEST_ID', 'PERIODO_DETECTADO_DESDE', 'PERIODO_DETECTADO_HASTA', 'ADVERTENCIAS_JSON', 'CANCELADO_EN', 'CANCELADO_POR', 'MOTIVO_CANCELACION'],
  CONCILIACIONES: ['CONCILIACION_ID', 'IMPORT_ID', 'MOVIMIENTO_ID', 'FACTURA_ID', 'IMPORTE_ASIGNADO', 'ESTADO', 'EVIDENCIA', 'DECISION', 'MOTIVO', 'CREADO_EN', 'CREADO_POR', 'DECIDIDO_EN', 'DECIDIDO_POR', 'DESHECHO_EN', 'DESHECHO_POR', 'REQUEST_ID'],
  CATEGORIAS: ['CATEGORIA_ID', 'NOMBRE', 'ACTIVA', 'PROVEEDORES_JSON', 'ACTUALIZADO_EN', 'ACTUALIZADO_POR', 'REQUEST_ID'],
  EXPORTACIONES: ['EXPORTACION_ID', 'PERIODO', 'COBERTURA', 'ESTADO', 'CARPETA_ID', 'CARPETA_URL', 'ARCHIVOS_JSON', 'MANIFEST_HASH', 'CREADO_EN', 'CREADO_POR', 'ERROR', 'REQUEST_ID'],
});

const DEFAULT_CATEGORIES = Object.freeze([
  'Componentes y repuestos', 'Logística y transporte', 'Software y servicios digitales', 'Suministros y consumibles',
  'Energía y telecomunicaciones', 'Alquileres y renting', 'Marketing y publicidad', 'Servicios profesionales',
  'Comisiones y gastos bancarios', 'Impuestos y tasas', 'Otros',
]);

const DEFAULT_CONFIG = Object.freeze([
  ['APP_VERSION', APP.VERSION, 'Versión de ReparaPRO Gastos'],
  ['APP_MODE', 'DRY_RUN', 'DRY_RUN impide archivo y registro definitivo'],
  ['APP_ALLOWED_USERS', APP.OWNER_EMAIL, 'Correos autorizados separados por coma'],
  ['APP_TIMEZONE', APP.TIMEZONE, 'Zona horaria de presentación'],
  ['APP_START_DATE', APP.START_DATE, 'Inicio mínimo de búsqueda en Gmail'],
  ['APP_MAX_BATCH_SIZE', String(APP.MAX_BATCH_SIZE), 'Máximo de correos por lote'],
  ['APP_SLICE_SIZE', String(APP.SLICE_SIZE), 'Correos por ejecución interna'],
  ['CARPETA_FACTURAS_ID', APP.INVOICE_FOLDER_ID, 'Carpeta A.2 - FA-GASTOS'],
  ['CARPETA_BANCOS_ID', APP.BANK_FOLDER_ID, 'Carpeta MOVIMIENTOS BANCARIOS'],
]);
